name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install modules
        uses: npi ci
      - name: Cypress run
      - uses: cypress-io/github-action@v6
        with: 
          browser: chrome
          headless: true
          start: npm run dev
